sudo: required
services:
- docker
env:
- EHRVIEWER_VER=0.0.0
before_script:
- wget -q https://$SOURCE_URL/source/marand/files/ehrviewer.war -O webapps/ehrviewer.war
script:
- envsubst < Dockerfile > Dockerfile.$EHRVIEWER_VER
- docker build -f Dockerfile.$EHRVIEWER_VER --tag marand-thinkehr-ehrviewer .
after_script:
- docker images
before_deploy:
- docker login $REGISTRY_URL -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag marand-thinkehr-ehrviewer "${REGISTRY_URL}"/marand-thinkehr-ehrviewer:${EHRVIEWER_VER}
deploy:
  provider: script
  script: docker push "${REGISTRY_URL}"/marand-thinkehr-ehrviewer:${EHRVIEWER_VER}
  on:
    branch: master
notifications:
  slack:
    secure: TazxaoqNq0MFDWuUzrOoK1h7yp2O9y2n0CzSeqbNPFDF79NlQBqfelWTc5nEyEyGvqy4/3M29PrTqDsCawMEWt/hdD+e7c+BQ49yIm8dJ21vrl5tFbZ5elISpVFgRaYgGZfZDjATRe8vuJH9Nq40TlCaTY5XFK67SCNa/eQy+qM99Oo6Ha+XUn/hbKJEKP4d3myiqaajzIduyGlyl3HHmIchSiQXsgKAjJODGU+Pzk75/RYf7icwje6FgM1MPnW1CfHZ7ioWJeTQrr7xNcSmDBJiLZimex3gKhp0QZh6ckdDLPionG06ZAVm5IZnNLaIUAW6vp7HbXC8C/YE/HdrZEalhF0+B/jEJ29Aa2/0zYDeK82poLbjJH7NGHMJQhpKLXH7MUc5gMMf2cSeL+5b6MZE5Vm4YHjZ1UZmqRtfniePUZAEKKD+jMcJdLeWFEcp7juZDEQpt+vOVYRP+opEq2sG5K5h9NHUXxj6SCGb+HeCGvQObgkRReKzz+wkzPyv35TJO1kBQH6knus5nSdIMDsh3ShoEvlrNcBKREloUGMJ8lA6Cs7FjhnUB3Nqj16OPNJIRp9DhUDwwq6tXESvRBISd2+kEIb6wHVeHUkoCFCxPbJSGV0CIhBpDUIU7Es5BwukCrRVMrZNb04A9YZQ+aIE/b7uexb5JeOXuSqNv8c=
